# Generated by Django 5.2.4 on 2025-07-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfricanLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
