# Generated by Django 5.2.4 on 2025-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='africanleaders',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='africanleaders',
            name='population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
